import Head from 'next/head'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link href="https://fonts.cdnfonts.com/css/helvetica-neue-5" rel="stylesheet"/>
        <link rel="stylesheet" href="globals.css"/>
      </Head>
      <body>{children}</body>
    </html>
  )
}
